# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
